name: IBM Detect Secrets Pipeline
on:
  pull_request:
  
jobs:
  secret-scanning:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install IBM Detect Secrets
        run: pip3 install --upgrade "git+https://github.com/ibm/detect-secrets.git@master#egg=detect-secrets"

      - name: Run IBM Detect Secrets - Scan
        run: detect-secrets scan --update .secrets.baseline
        
      - name: Run IBM Detect Secrets - Audit
        run: detect-secrets audit --report --fail-on-unaudited --fail-on-live --fail-on-audited-real .secrets.baseline
